[snippy][packaging] Fix whisper in release bundle
Whishper wasn't being properly patchelf-d and libz wasn't
vendored:

error: could not load library: libz.so.1: cannot open shared object file: No such file or directory

With spike we got lucky because all it depends on is already in the
closure loaded by llvm-snippy.